doctors = [
    {
        'name': 'Dr. Gero',
        'email': 'dr.gero@anime.com',
        'phone_number': '1234567890',
        'date_of_birth': '1955-05-25',
        'gender': 'Male',
        'specialization': 'Cyborg Engineering',
    },
    {
        'name': 'Dr. Kurogane',
        'email': 'dr.kurogane@anime.com',
        'phone_number': '2345678901',
        'date_of_birth': '1980-10-10',
        'gender': 'Male',
        'specialization': 'Alchemy',
    },
    {
        'name': 'Dr. Tsunade',
        'email': 'dr.tsunade@anime.com',
        'phone_number': '3456789012',
        'date_of_birth': '1994-08-15',
        'gender': 'Female',
        'specialization': 'Medical Ninjutsu',
    },
    {
        'name': 'Dr. Hyouga',
        'email': 'dr.hyouga@anime.com',
        'phone_number': '4567890123',
        'date_of_birth': '1975-12-30',
        'gender': 'Male',
        'specialization': 'Pediatrician',
    },
    {
        'name': 'Dr. Ichiraku',
        'email': 'dr.ichiraku@anime.com',
        'phone_number': '5678901234',
        'date_of_birth': '1985-01-01',
        'gender': 'Male',
        'specialization': 'Noodle Specialist',
    },
]

patients = [
    {
        'name': 'Sakura Haruno',
        'email': 'sakura@anime.com',
        'phone_number': '6789012345',
        'date_of_birth': '1999-03-28',
        'gender': 'Female',
    },
    {
        'name': 'Naruto Uzumaki',
        'email': 'naruto@anime.com',
        'phone_number': '7890123456',
        'date_of_birth': '1999-10-10',
        'gender': 'Male',
    },
    {
        'name': 'Saitama',
        'email': 'saitama@anime.com',
        'phone_number': '8901234567',
        'date_of_birth': '1988-04-20',
        'gender': 'Male',
    },
    {
        'name': 'Hinata Hyuga',
        'email': 'hinata@anime.com',
        'phone_number': '9012345678',
        'date_of_birth': '2000-06-25',
        'gender': 'Female',
    },
    {
        'name': 'Goku',
        'email': 'goku@anime.com',
        'phone_number': '0123456789',
        'date_of_birth': '1980-04-16',
        'gender': 'Male',
    },
    {
        'name': 'Luffy',
        'email': 'luffy@anime.com',
        'phone_number': '1234567891',
        'date_of_birth': '1997-05-05',
        'gender': 'Male',
    },
    {
        'name': 'Nami',
        'email': 'nami@anime.com',
        'phone_number': '2345678910',
        'date_of_birth': '1998-07-03',
        'gender': 'Female',
    },
    {
        'name': 'Edward Elric',
        'email': 'edward@anime.com',
        'phone_number': '3456789012',
        'date_of_birth': '1900-09-08',
        'gender': 'Male',
    },
    {
        'name': 'Kenshin Himura',
        'email': 'kenshin@anime.com',
        'phone_number': '4567890123',
        'date_of_birth': '1850-10-02',
        'gender': 'Male',
    },
    {
        'name': 'Yoruichi Shihouin',
        'email': 'yoruichi@anime.com',
        'phone_number': '5678901234',
        'date_of_birth': '1990-11-01',
        'gender': 'Female',
    },
]
